export struct Translations {
    // main window sidebar
    app-name: string,
    library: string,
    all-books: string,
    reading: string,
    completed: string,
    favorites: string,
    // main window header
    books: string,
    contents: string,
    grid: string,
    list: string,
    // Dialog
    cancel: string,
    accept: string,
    delete: string,
    quit: string,
    save: string,
    edit: string,
    select: string,
    select-all: string,
    select-none: string,
    disable: string,
    enable: string,
    // Content dialog
    field-title: string,
    field-author: string,
    field-language: string,
    new-content: string,
    new-book: string,
    // People dialog
    new-person: string,
    field-name: string,
    field-role: string,
    new-role: string,
}

export global Tr {
    in property <Translations> t: {
        // main window sidebar
        app-name: "App",
        library: "Library",
        all-books: "All books",
        reading: "Reading",
        completed: "Completed",
        favorites: "Favorites",
        // main window header
        books: "Books",
        contents: "Contents",
        grid: "Grid",
        list: "List",
        // Dialog
        cancel: "Cancel",
        accept: "OK",
        delete: "Delete",
        quit: "Quit",
        save: "Save",
        edit: "Edit",
        select: "Select",
        select-all: "Select All",
        select-none: "Select None",
        disable: "Disable",
        enable: "Enable",
        // Content dialog
        field-title: "Title",
        field-author: "Author",
        field-language: "Language",
        new-content: "New Content",
        new-book: "New Book",
        // People dialog
        new-person: "New Person",
        field-name: "Name",
        field-role: "Role",
        new-role: "Role",
    };
}
